sudo: false
language: go
go:
  - 1.8
  - 1.9
  - tip
before_install:
  - openssl aes-256-cbc -k "$super_secret_password" -in parameters.json.enc -out parameters.json -d
  - curl -L -s https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
install:
  - dep ensure
script:
  - make fmt lint cov
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    secure: KFHezm3/3rfoh9n5L1zhr+SJkbgL08ugg0otSykzSIgc7AaUlb3CLiBwIZ/Yys20MajW2/MAz6uUtD5W/XBJ+Cz7bGmv/q26cgDWPexD//xGgF9sumIBjcbLRF1vsvjqBf9K9lGPRYffU+zOVkqZUIG2ojpugE3yep+PhzhsnQpMjLju2YFmKb0dEbBhJMb/ZCUOzVwNNJBsxnp7CmoOCvsrOODhKHRb58Iy83VKYc9cxX5IhLdrdllybsIyQgvr39Zr74uyMt5CJtoFBlWEUXuqkcjHHdA63rtrX3WFebjx46UkYnSUofrlQ8deYdaUYeDMtM1GTR4KdX903SxuqpYz65oIsI1KOJf9xV2fNI4GGvN4UOryp3DpDlFjwnwsx6uPzDqQnqHlk8MUxlkuLayvzO3CO4LBVbT8BRS8x138qU1FvAx48SwiqFeuefInj26Z0H2MyW4i/jEiZh9P37M3qrw84G/kCehpZhhyLkeGtjg3Ny+wnW/57D4EHlWk1R5eybwjehAidfnZ+dRLjtboeOF5iL3Nd43GzQVog4YVqzrVYSw5Yz40JjTQwTjmslPbFAHIEvdvTeAvmR+MsdiKa7joE7K0z5agTu73sv8quAY5rrXAPZ2Bcff3o8kXlFP41IsAdGIaMKqW78B4e6olgaSlbFOrvW24/lNGnWI=
